### امیرحسین مهدی‌نژاد - شماره دانشجویی ۸۱۰۸۰۰۰۵۸ - تمرین سری اول الگوریتم‌های یادگیری ماشین

# پاسخ سوال‌های دوم و چهارم

## اضافه کردن کتابخانه‌های مورد استفاده

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from Utiles import normalizer
from scipy.optimize import minimize

## خواندن دیتاست سرطان سینه

In [2]:
X, y = load_breast_cancer(return_X_y=True)
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [3]:
X.shape

(569, 30)

## تقسیم داده‌ها به دو بخش آموزش و آزمون

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Utiles نرمالسازی با استفاده از تابع پیاده‌سازی شده در فایل

In [5]:
X_train, X_test = normalizer(X_train, X_test)
X_train

array([[-0.09864553, -0.20478061, -0.09542961, ..., -0.12102497,
         0.13018218,  0.05394451],
       [-0.12759406, -0.03332305, -0.13241922, ..., -0.11755418,
         0.06863275, -0.03654075],
       [-0.14035104, -0.02486854, -0.14038622, ..., -0.10882566,
         0.03298636, -0.10745808],
       ...,
       [ 0.08927459,  0.13170908,  0.0725886 , ..., -0.05958167,
         0.00637039,  0.00213546],
       [ 0.15060623,  0.20543244,  0.14158846, ...,  0.19522933,
        -0.10009349, -0.03122195],
       [ 0.02352708,  0.02653491,  0.01596604, ...,  0.15055579,
         0.02561944, -0.01336129]])

## اضافه کردن ستون یک سمت چپ داده‌ها

In [6]:
X_train, X_test = np.c_[np.ones(X_train.shape[0]), X_train], np.c_[np.ones(X_test.shape[0]), X_test]
X_train

array([[ 1.        , -0.09864553, -0.20478061, ..., -0.12102497,
         0.13018218,  0.05394451],
       [ 1.        , -0.12759406, -0.03332305, ..., -0.11755418,
         0.06863275, -0.03654075],
       [ 1.        , -0.14035104, -0.02486854, ..., -0.10882566,
         0.03298636, -0.10745808],
       ...,
       [ 1.        ,  0.08927459,  0.13170908, ..., -0.05958167,
         0.00637039,  0.00213546],
       [ 1.        ,  0.15060623,  0.20543244, ...,  0.19522933,
        -0.10009349, -0.03122195],
       [ 1.        ,  0.02352708,  0.02653491, ...,  0.15055579,
         0.02561944, -0.01336129]])

## پیاده‌سازی تابع هزینه

\begin{align*}& J(\theta) = \dfrac{1}{m} \sum_{i=1}^m \mathrm{Cost}(h_\theta(x^{(i)}),y^{(i)}) \newline & \mathrm{Cost}(h_\theta(x),y) = -\log(h_\theta(x)) \; & \text{if y = 1} \newline & \mathrm{Cost}(h_\theta(x),y) = -\log(1-h_\theta(x)) \; & \text{if y = 0}\end{align*}

$$Loss = Error(Y - \widehat{Y}) +  \lambda \sum_1^n w_i^{2}$$

In [7]:
def compute_cost(theta, X, Y):
    m = X.shape[0]
    lamda = 0.01
    return -1/m * sum(np.multiply(Y, np.log( 1/(1 + np.exp(-np.matmul(X, theta))))) + np.multiply( (1 - Y), np.log(1 - 1/(1 + np.exp(-np.matmul(X, theta)))))) + (lamda/(2*m))*sum(np.array(theta[1:])**2)

## پیاده‌سازی مشتق تابع هزینه

In [8]:
def gradient(theta, X, Y):
    m = X.shape[0]
    lamda = 0.01
    temp = theta
    temp[0] = 0
    return np.matmul( np.transpose(1/(1 + np.exp(-np.matmul(X, theta))) - Y ), X) / m + (lamda/m)*sum(theta)

In [11]:
theta = np.zeros(X_train.shape[1])
rounds = [i+1 for i in range(iteration)]

## پیدا کردن مقدار بهینه با استفاده از تابع مینی‌مایز

In [12]:
result = minimize(compute_cost, x0=np.zeros(X_train.shape[1]), args=(X_train, y_train), method ='CG', jac=gradient)
theta = result.x

In [14]:
compute_cost(theta, X_train, y_train)

0.32706404574857334

## استفاده از کتابخانه‌های از پیش تعریف شده برای مقایسه‌ی نتایج

In [15]:
from sklearn.linear_model import LogisticRegression

regr = LogisticRegression()
regr.fit(X_train, y_train)
print(regr.score(X_train, y_train))
regr.coef_

0.9692307692307692


array([[ 7.75301150e-06, -1.49219149e+00, -1.43843735e+00,
        -1.47099225e+00, -1.23716659e+00, -6.14740711e-01,
        -4.52501507e-01, -1.29494461e+00, -1.87271405e+00,
        -4.96342622e-01,  6.28933095e-01, -8.78764771e-01,
        -5.80680695e-02, -6.69279753e-01, -6.03628851e-01,
         1.09634407e-01,  7.27162703e-01,  2.80726389e-01,
        -1.02223972e-01,  1.54000601e-01,  4.74934402e-01,
        -2.33421697e+00, -2.24358490e+00, -2.15913670e+00,
        -1.82664977e+00, -1.67067647e+00, -8.70029089e-01,
        -1.40633471e+00, -2.64837782e+00, -1.46233515e+00,
        -5.58933606e-01]])

In [16]:
regr.predict(X_train[0:2])

array([1, 1])

## اجرا برای داده‌ی تست

In [17]:
compute_cost(theta, X_test, y_test)

0.2779286462646651

In [18]:
regr.score(X_test, y_test)

0.9473684210526315

نتیجه‌ی ما بهتر بود