### امیرحسین مهدی‌نژاد - شماره دانشجویی ۸۱۰۸۰۰۰۵۸ - تمرین سری اول الگوریتم‌های یادگیری ماشین

# پاسخ سوال پنجم

## اضافه کردن کتابخانه‌های مورد استفاده

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from Utiles import normalizer
from numpy.linalg import inv

## خواندن دیتاست بوستون

In [3]:
X, y = load_boston(return_X_y=True)
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

## تقسیم داده‌ها به آموزش و آزمون، نرمالسازی و اضافه کردن ستون یک سمت چپ

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train, X_test = normalizer(X_train, X_test)
X_train, X_test = np.c_[np.ones(X_train.shape[0]), X_train], np.c_[np.ones(X_test.shape[0]), X_test]
X_train

array([[ 1.        , -0.02553708, -0.11908416, ...,  0.30090057,
        -0.23861691,  0.1258244 ],
       [ 1.        , -0.03597612, -0.11908416, ...,  0.27962397,
         0.09962506, -0.13438531],
       [ 1.        , -0.03235928, -0.11908416, ...,  0.00302823,
         0.09657397, -0.09575397],
       ...,
       [ 1.        , -0.03561544,  0.48091584, ..., -0.00761007,
         0.03376193, -0.20033454],
       [ 1.        , -0.03439188, -0.11908416, ..., -0.05016326,
         0.09962506,  0.03862793],
       [ 1.        , -0.03512325, -0.11908416, ..., -0.06080156,
         0.09470802,  0.0954712 ]])

## پیاده‌سازی ضرب ماتریس معادله نرمال

\begin{align*}& \theta = \left( X^TX + \lambda \cdot L \right)^{-1} X^Ty \newline& \text{where}\ \ L = \begin{bmatrix} 0 & & & & \newline & 1 & & & \newline & & 1 & & \newline & & & \ddots & \newline & & & & 1 \newline\end{bmatrix}\end{align*}

In [8]:
theta = np.matmul(inv(np.matmul(np.transpose(X_train), X_train)), np.matmul(np.transpose(X_train), y_train))

## بررسی مقدار بدست آمده

In [9]:
theta

array([ 22.52227723,  -9.66065182,   5.5162249 ,   1.7452387 ,
         2.17423862,  -9.32240741,  17.91265534,   1.03004015,
       -14.88182557,   7.37311325,  -7.09537369,  -9.54510083,
         4.00660829, -20.01820497])